MSDKUI-2388: Update documentation
heremaps/msdkui-ios pull request #204
Opened 2021-04-15 10:06 UTC by ephmoc

Signed-off-by: Krzysztof Hubaczek <19998177+ephmoc@users.noreply.github.com>

2021-04-16 15:25 UTC, stefan-troyke reviewed
Looks good, but I would prefer datasun approves this.

2021-04-20 08:49 UTC, datasun requested changes

2021-04-20 08:49 UTC, datasun commented on Documentation/Guides/UserGuide.md
> +- [HERE Mobile SDK UI Kit (MSDKUI) - User Guide](#here-mobile-sdk-ui-kit-msdkui---user-guide)
We can remove line 9 + 10 as they are redundant.

2021-04-20 09:15 UTC, stefan-troyke approved these changes

2021-04-20 09:19 UTC, ephmoc commented on Documentation/Guides/UserGuide.md
> +- [HERE Mobile SDK UI Kit (MSDKUI) - User Guide](#here-mobile-sdk-ui-kit-msdkui---user-guide)
Done

2021-04-20 09:21 UTC, datasun approved these changes

2021-04-20 09:24 UTC, merged